classes:
- system.linux.system.repo.mcp.salt
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.apt_mirantis.openstack
- system.linux.system.repo.mcp.apt_mirantis.ubuntu
- system.linux.system.repo.mcp.apt_mirantis.glusterfs
- system.linux.system.repo.mcp.apt_mirantis.saltstack_2016_3
- system.openssh.client.lab
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.salt_pki
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.backupninja.client.single
- system.xtrabackup.server.single
- system.cassandra.backup.server.single
- system.zookeeper.backup.server.single
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.opencontrail_analytics_cluster
- system.reclass.storage.system.opencontrail_control_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- system.reclass.storage.system.openstack_benchmark_single
- system.reclass.storage.system.openstack_control_upgrade_single
- system.reclass.storage.system.stacklight_log_cluster
- system.reclass.storage.system.stacklight_telemetry_cluster
- system.reclass.storage.system.stacklightv2_server_cluster
- system.reclass.storage.system.oss_cluster
- system.reclass.storage.system.cicd_control_cluster
- system.reclass.storage.system.ceph_mon_cluster
- system.reclass.storage.system.ceph_rgw_cluster
- service.jenkins.client
- system.jenkins.client.credential.salt
- system.jenkins.client.job.deploy.openstack
- cluster.snv.infra.maas
- cluster.snv.infra
- cluster.snv.infra.networking.config
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/Mirantis/mk-lab-salt-model.git"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$fKPrBHsC$BLksNU0O3ET3pP39iW2e3VROfQX8pEh0SeBIcLzcqxvrGmOSAbKsFOa3kIZq2bk/xKzcOMjC5HataTlPfGj.d0"
    salt_master_host: ${_param:infra_config_deploy_address}
    backupninja_backup_host: ${_param:infra_kvm_node03_address}
    jenkins_git_url: 'git@cfg01:/home/repo'
    jenkins_gerrit_url: ${_param:jenkins_git_url}
    salt_api_password: 1pJTA7hgsTVngU456TRB0fGD8pskrytt
    jenkins_salt_api_url: "http://${_param:salt_master_host}:6969"
    jenkins_pipeline_library_url: git@cfg01:/home/repo/mcp-ci/pipeline-library
    jenkins_pipelines_branch: '2018.1'
  jenkins:
    client:
      lib:
        pipeline-library:
          url: ${_param:jenkins_pipeline_library_url}
          branch: ${_param:jenkins_pipelines_branch}
      master:
        host: ${_param:salt_master_host}
        port: 8081
        password: r00tme
  salt:
    master:
      command_timeout: 600
      user:
        deploy:
          permissions: ${_param:salt_master_api_permissions}
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
      backup: true
    minion:
      backup: true
  reclass:
    storage:
      data_source:
        engine: local
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
        infra_kvm_node03:
          classes:
          - system.backupninja.server.single
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
          classes:
          - system.ceph.backup.server.single
          - system.backupninja.server.single
        stacklight_log_node01:
          classes:
          - system.elasticsearch.client.single
          - system.kibana.client.single
        opencontrail_control_node01:
          classes:
          - cluster.${_param:cluster_name}.opencontrail.control_init
        openstack_control_node01:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_control_node02:
          params:
            linux_system_codename: xenial
        openstack_control_node03:
          params:
            linux_system_codename: xenial
        openstack_database_node01:
          params:
            linux_system_codename: xenial
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
        openstack_database_node02:
          params:
            linux_system_codename: xenial
        openstack_database_node03:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node01:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node02:
          params:
            linux_system_codename: xenial
        openstack_message_queue_node03:
          params:
            linux_system_codename: xenial
        openstack_proxy_node01:
          params:
            linux_system_codename: xenial
        openstack_proxy_node02:
          params:
            linux_system_codename: xenial
        openstack_compute_rack01:
          name: ${_param:openstack_compute_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          repeat:
            count: 2
            start: 1
            digits: 3
            params:
              single_address:
                value: ${_param:openstack_compute_rack01_single_subnet}.<<count>>
                start: 101
              tenant_address:
                value: ${_param:openstack_compute_rack01_tenant_subnet}.<<count>>
                start: 101
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
        ceph_osd_rack01:
          name: ${_param:ceph_osd_rack01_hostname}<<count>>
          domain: ${_param:cluster_domain}
          classes:
            - cluster.${_param:cluster_name}.ceph.osd
          repeat:
            count: 5
            start: 1
            digits: 3
            params:
              single_address:
                value: ${_param:ceph_osd_rack01_single_subnet}.<<count>>
                start: 201
              backend_address:
                value: ${_param:ceph_osd_rack01_backend_subnet}.<<count>>
                start: 201
          params:
            salt_master_host: ${_param:reclass_config_master}
            ceph_crush_parent: rack01
            linux_system_codename: xenial

